[global]
dataFrameSerialization = "legacy"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 10

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#2e8b57"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730" 